services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - "../db:/docker-entrypoint-initdb.d:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=crunchit
    ports:
      - 3306:3306
volumes:
  db_data: